export GIT_COMMITTER_NAME="zhanjun"
export GIT_COMMITTER_EMAIL="zhanjun@gmail.com"
export GIT_AUTHOR_NAME="Jun"
export GIT_AUTHOR_EMAIL="zhanjun@gmail.com"
export GIT_SSH_COMMAND="ssh -i /data/gitkey"
